autogen: Add missing indirection through file cache
- This commit is ported from mlkem-native PR 1284
- This commit fixed following:

- Symptom:

```
  rm mlkem/src/native/aarch64/src/arith_native_aarch64.h
  autogen
```

fails with

```
  FileNotFoundError: [Errno 2] No such file or directory: \
     'mlkem/src/native/aarch64/src/arith_native_aarch64.h'
```

- Context:

- A previous commit has introduced an internal file cache to autogen.
  During main operation of autogen, all file read/write operations
  should go through this in-memory cache.

- Issue:

- Two instance of direct FS reads via `open(...)` were overlooked
  when this change was introduced, leading to an attempt to load
  a file from the file system which only exists in the cache.

- This commit fixes this by calling the file cache `read_file()`
  operation intead.

Signed-off-by: willieyz <willie.zhao@chelpis.com>